sudo: required
dist: xenial
language: python

# python versions
python:
  - '3.7.7'

# command to install dependencies
install:
  - pip install -r requirements.txt

# To run tests
script: coverage run --source='.' manage.py test polls

# send coverage report to coveralls
after_success:
    coveralls